### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by DarkMoonCBK** [exosiscrypto/exosis#1]
libbitcoin_server.a(libbitcoin_server_a-activemasternode.o): In function CActiveMasternode::ManageStateInitial(CConnman&)':
activemasternode.cpp:(.text+0x29f7): undefined reference toCConnman::AllNodes'
libbitcoin_server.a(libbitcoin_server_a-masternodeman.o): In function CMasternodeMan::ProcessMasternodeConnections(CConnman&)':
masternodeman.cpp:(.text+0x861c): undefined reference toCConnman::AllNodes'
libbitcoin_server.a(libbitcoin_server_a-masternode-sync.o): In function CMasternodeSync::SwitchToNextAsset(CConnman&)':
masternode-sync.cpp:(.text+0x1171): undefined reference toCConnman::AllNodes'
libbitcoin_server.a(libbitcoin_server_a-masternode-sync.o): In function CMasternodeSync::ClearFulfilledRequests(CConnman&)':
masternode-sync.cpp:(.text+0x301c): undefined reference toCConnman::AllNodes'
collect2: error: ld returned 1 exit status
Makefile:3816: recipe for target 'exosisd' failed

-------------------------------------------------------------------------------------------------------------------
./configure --disable-tests --without-gui --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX CXXFLAGS="-fPIC" CPPFLAGS="-fPIC"

ubuntu 16

**Comment by exosiscrypto** [comment]
Hi
Try building the depends system. It builds fine for me on ubuntu16
use a similar configure to this
./configure --prefix=/path/toexosis/depends/x86_64-pc-linux-gnu --disable-tests --disable-bench --disable-gui-tests

**Comment by DarkMoonCBK** [comment]
Compile completed. 
make -j4

but make -j6 Cannot compile

**Comment by yunchiri** [comment]
@DarkMoonCBK  what diffirent make -j4 make -j6

me too make -j4 compile ok , I can't understand
