### ISSUE TITLE
no peers

### ISSUE THREAD

**Issue by Twente-Mining** [exosiscrypto/exosis#13]
QT wallet does not sync up. no peers.

**Comment by rhenrhee** [comment]
addnode=95.179.176.148
addnode=149.202.121.129
addnode=94.130.129.84
addnode=[2a01:4f8:13b:3aa7::2]
addnode=3.219.58.63
addnode=164.68.102.176
addnode=185.182.193.40
addnode=105.186.9.74:50415
addnode=105.186.9.74:53517
addnode=105.186.9.74:56231
addnode=105.186.9.74:61463
addnode=105.186.9.74:64442
addnode=105.227.81.119:55737
addnode=109.236.80.33:54757
addnode=122.164.211.242:10967
addnode=122.164.211.242:12064
addnode=149.202.121.129:59500
addnode=164.68.102.176:12330
addnode=18.191.69.189:44974
addnode=185.182.193.40:36070
addnode=185.50.24.19:40068
addnode=188.42.33.124:30093
addnode=195.181.214.183:57314
addnode=195.201.184.178:37976
addnode=195.201.213.212:34456
addnode=197.242.155.220:52490
addnode=212.8.252.27:53015
addnode=37.97.240.210:47930
addnode=40.140.51.137:52832
addnode=40.140.51.137:54578
addnode=40.140.51.137:55578
addnode=40.140.51.137:56682
addnode=40.140.51.137:63021
addnode=46.212.211.210:55698
addnode=46.212.211.210:56664
addnode=46.212.211.210:58100
addnode=46.23.35.70:61987
addnode=5.9.13.72:52776
addnode=51.68.204.201:38352
addnode=54.189.168.55:58904
addnode=70.91.250.149:41558
addnode=94.130.129.84:48970
addnode=95.179.186.109:60198

**Comment by exosiscrypto** [comment]
Use this node to sync 209.250.247.116
For more details check this topic https://forum.exosis.org/d/12-how-to-connect-to-peers
