### ISSUE TITLE
compile fails 

### ISSUE THREAD

**Issue by alanb22** [exosiscrypto/exosis#2]
Generated bench/data/block413567.raw.h
  CXX      bench/bench_bench_exosis-checkblock.o
  CXX      bench/bench_bench_exosis-checkqueue.o
  CXX      bench/bench_bench_exosis-Examples.o
  CXX      bench/bench_bench_exosis-rollingbloom.o
  CXX      bench/bench_bench_exosis-crypto_hash.o
  CXX      bench/bench_bench_exosis-ccoins_caching.o
  CXX      bench/bench_bench_exosis-mempool_eviction.o
  CXX      bench/bench_bench_exosis-verify_script.o
  CXX      bench/bench_bench_exosis-base58.o
  CXX      bench/bench_bench_exosis-lockedpool.o
  CXX      bench/bench_bench_exosis-perf.o
  CXX      bench/bench_bench_exosis-prevector_destructor.o
  CXX      bench/bench_bench_exosis-coin_selection.o
  CXXLD    bench/bench_exosis
  CXX      qt/qt_exosis_qt-bitcoin.o
In file included from ./qt/paymentserver.h:35:0,
                 from qt/bitcoin.cpp:27:
./qt/paymentrequestplus.h:10:10: fatal error: qt/paymentrequest.pb.h: No such file or directory
 #include "qt/paymentrequest.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

./configure --disable-tests --with-incompatible-bdb

all depends are met

ubuntu 8.04

**Comment by exosiscrypto** [comment]
Hi
qt/paymentrequest.pb.h is generated by protobuf at compile time. Please check your dependencies again
Are you using the depends system to build?

**Comment by alanb22** [comment]
Hi,
I am aware that libprotobuf is used for qt, have compiled a number of qt wallets on this system and have not had this problem.
I tried purging the packages and reinstalling
sudo apt purge libprotbuf-dev protobuf-compiler && sudo apt install libprotbuf-dev protobuf-compiler 

 dpkg -L protobuf
output:
 libprotobuf-dev_3.0.0-9.1ubuntu1_amd64.deb
 protobuf-compiler_3.0.0-9.1ubuntu1_amd64.deb

pkg-config --list-all | grep protobuf
output:
protobuf-lite                  Protocol Buffers - Google's Data Interchange Format
protobuf                       Protocol Buffers - Google's Data Interchange Format

export PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig
 
./autogen.sh && ./configure --disable-tests --with-incompatible-bdb && make

not using depends as not trying to build cross platform 
it builds all depends for the wallet from sources and packages them in the main binary?

any pointers to what i'm missing would be appreciated
