### ISSUE TITLE
Unable to run/compile on Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by RAlvarez66** [exosiscrypto/exosis#6]
Hello,

Your compiled binaries and source code have the following issues:

1) Your compiled binaries (Release) can't be run inside a clean Ubuntu 16.04 installation.

2) On Ubuntu 18.04, your wallet fails to launch (wallet from your released binaries).

3) On both Ubuntu 16.04 and 18.04 the compilation fails even after all the dependencies have been installed. The only way to compile is by using the switch --without-gui which then means no gui wallet.

4) Due to the previous errors, it seems that the wallet can not be run on Ubuntu (the daemon works fine if compiled with the above switch).

5) On Ubuntu 18.04, unless the switch --disable-tests is used with ./configure, the compilation fails.

**Comment by exosiscrypto** [comment]
New version it is updated check
